### ISSUE TITLE
problem on code

### ISSUE THREAD

**Issue by msksanjay77** [adafruit/Adafruit_SSD1306#101]
I had verify the code of adafruit ssd1306 128*64 i2c. I got a compiling error 

> 

 (height incorrected,please fix Adafruit_ssd1306.h!).

`Then` i check the adafruit h file,everything is good.I don't know how to fix it. Help me to fix it quickly.

**Comment by mithbre** [comment]
Comment out this line:
https://github.com/adafruit/Adafruit_SSD1306/blob/master/Adafruit_SSD1306.h#L74
Uncomment this line:
https://github.com/adafruit/Adafruit_SSD1306/blob/master/Adafruit_SSD1306.h#L73

Then recompile your project.

**Comment by PaintYourDragon** [comment]
Library v1.2 eliminated the "edit the .h file" requirement -- display size can now be specified in the constructor (see examples).
