### ISSUE TITLE
Please give the Pin Number for the I2C SSD1306 Example using the I2C

### ISSUE THREAD

**Issue by Manyyack** [adafruit/Adafruit_SSD1306#105]
The example is quite unclear because nowhere the pin number for the I2C is mentioned.

**Comment by TyrantFox** [comment]
The I2C pins are determined by your board. Look for pins labeled SCL and SDA on your board or in its documentation. If you're using an Uno the pins are A5 (SCL) and A4 (SDA). See http://www.pighixxx.com/test/wp-content/uploads/2017/05/uno.png for example.

**Comment by ladyada** [comment]
resolved!
