### ISSUE TITLE
SSD1306 used with CC1310 , showing random pixels

### ISSUE THREAD

**Issue by aloo0361** [adafruit/Adafruit_SSD1306#113]
Hi, I am trying to interface SSD1310 with CC1310 MCU. I am able to light up my OLED screen but the screen displays random pixels. I have used the same configuration as used in the Adafruit library. And I am using S/W SPI (4 wire) for communication. Please help me resolve this issue

**Comment by aloo0361** [comment]
Hi, I am trying to interface SSD1310 with CC1310 MCU. I am able to light up my OLED screen but the screen displays random pixels. I have used the same configuration as used in the Adafruit library. And I am using S/W SPI (4 wire) for communication. Please help me resolve this issue

**Comment by dhalbert** [comment]
Could you start a support thread in https://forums.adafruit.com? This is probably a usage issue rather than a bug. Thanks.

**Comment by aloo0361** [comment]
Actually I am not using an Adafruit product nor am I using the source code,
I have taken assistance from Adafruit library and written my code, but I am
unsure as to whether this is a software issue or a hardware issue.
Where can I get assistance regarding this.
