### ISSUE TITLE
Speed up the I2C display by 5.55% by increasing the transmission size

### ISSUE THREAD

**Issue by mleibman** [adafruit/Adafruit_SSD1306#114]
The standard `Wire` interface has a 32-byte buffer for sending data to I2C devices, but this library sends data in 16-byte chunks. Making it send the data in 32-byte chunks could increase the efficiency quite a bit by reducing the overhead from repeated device address and control byte transmissions.

Say, you had to transfer data for a 128x32 display. That's 512 bytes of data.

Sending it 16 bytes at a time, that's 32 transmissions with +2 bytes of overhead for each, adding 64 bytes of overhead, totaling 576 bytes.
Sending it 32 bytes at a time would result in 16 transmissions, totaling 544 bytes, or 5.55% smaller and, therefore, **5.55% faster**.

Of course, sending the whole buffer in one transmission (see https://github.com/sparkfun/SparkFun_Micro_OLED_Arduino_Library/issues/18) would be best, but the `Wire` interface doesn't support that, so it'd have to be device-specific.

**Comment by PaintYourDragon** [comment]
Implemented in v1.2. Thanks!
