### ISSUE TITLE
How to blink cursor? 

### ISSUE THREAD

**Issue by eRony-232** [adafruit/Adafruit_SSD1306#115]
I have built Digital clock using SSD1306(OLED Display Blue I2C 128x64 0.96).

I wish to set time by button.
In this case when select hour,min,sec,
Then it will be blink.

Dose Adafruit_SSD1306 has such option?

Regards,
eRony

**Comment by ladyada** [comment]
it doesnt! you'll have to draw it by hand by inverting the character (swapping fg and bg color) and drawing it
