### ISSUE TITLE
Guru Meditation Error: Core  1 panic'ed (IntegerDivideByZero). Exception was unhandled.

### ISSUE THREAD

**Issue by mrohner** [adafruit/Adafruit_SSD1306#125]
- Arduino board:  esp32doit-devkit-v1
- PlatformIO
- Adafruit_SSD1306 1.2.5

Program stops with devide by zero error when executing  display.begin(SSD1306_SWITCHCAPVCC, 0x3C);  

I did change the Adafruit_SSD1306.h file to reflect the screen size 
 #define SSD1306_128_64
//#define SSD1306_128_32
//#define SSD1306_96_16

Error:
Guru Meditation Error: Core  1 panic'ed (IntegerDivideByZero). Exception was unhandled.
Core 1 register dump:
PC      : 0x4011f1a3  PS      : 0x00060730  A0      : 0x8011ed48  A1      : 0x3ffb1f10  
A2      : 0x3ffc1c60  A3      : 0x00000000  A4      : 0x02625a00  A5      : 0x0000000c  
A6      : 0x00000064  A7      : 0x3ffc1c60  A8      : 0x8011ede8  A9      : 0x3ffb1ef0  
A10     : 0x00000000  A11     : 0x00000001  A12     : 0x3ffc6e70  A13     : 0x00000000  
A14     : 0x00000000  A15     : 0x00000000  SAR     : 0x00000016  EXCCAUSE: 0x00000006  
EXCVADDR: 0x00000000  LBEG    : 0x4000c2e0  LEND    : 0x4000c2f6  LCOUNT  : 0x00000000  

Backtrace: 0x4011f1a3:0x3ffb1f10 0x4011ed45:0x3ffb1f30 0x400d2602:0x3ffb1f50 0x400d18f2:0x3ffb1f80 0x4011f94b:0x3ffb1fa0

**Comment by ladyada** [comment]
please update to version 1.2.7 of this library

**Comment by maxim25111** [comment]
I did figure out what make that error in my code. 
Adafruit did make an update in code with
Ssd.begin( );
And then should be added screen size. 
Other wise program is crash and is displaying this message.

**Comment by PaintYourDragon** [comment]
@maxim25111 The library should be backwards-compatible with old code and has been tested that way. Were you calling any other SSD1306 functions before calling begin()? If not, can you copy your code here (or a subset) that was causing the problem?

**Comment by PaintYourDragon** [comment]
@maxim I see you're using 1.2.5. Try instead with the latest release, 1.2.9.

**Comment by maxim25111** [comment]
I try all release, this same problem. 
Earlier before an update my code on heltec esp1306 was working great. 
After update, I find out that I need add screen size and option &Wire. Then one error go. But then my screen start behaving wired. Every 6 rows, lines was mowed 5 pixels in to the left side, that when I have picture on the screen, left side go to the end of the right side. 
 After 2 days, trying find error in code on library of esp1306, I delete whole folder, and I downloaded fresh version from git repo.
 Shock! After trying upload sketch again, my old code start again working normally. 
 I check none more time at library from esp1306,to specific file 'for this moment I don't remember file name, but it was something to do with Wire speed' and this file was written with more complex code.
Anyway, is working now. 
Problem was in esp1306 folder in hardware.
