### ISSUE TITLE
Multiple displays sharing a buffer, do we need a setBuffer() call?

### ISSUE THREAD

**Issue by smillerVP** [adafruit/Adafruit_SSD1306#137]
For very small machines (atmega32u4) it seems not easy to run multiple 128x64 displays with the new dynamic buffer allocation logic since I see no way to avoid the malloc command?  In many use cases there is no need for separate and permanent buffers for these small displays because it's pretty trivial to rewrite the entire image for each update cycle.  At it stands, with two displays and a very simple sketch I am able to consistently fail a second allocation if I'm going to use begin() to initialize two displays.  Maybe I missed it, and would love to hear another opinion.  (BTW - getting rid of the splash tables is not sufficient, and not allowed).

Locally, to permit use of a single global buffer, I altered my copies of the library to add a setBuffer() call without touching the begin() call line.   I prefer a new setBuffer() call because begin() already has code to protect from reallocating when there's a buffer already present and it seemed overkill to alter begin()'s call line.  Unfortunately,  I believe a private flag variable has to be added to signal when an allocation was actually done so the setBuffer() doesn't overwrite it and so the free() call can be used or avoided as necessary.  That silly flag threw a bunch of little changes through the code and so I'm undecided about whether to upload my stuff yet or see if there's a better way to know not to free something the display object didn't allocate.

**Comment by ladyada** [comment]
we had to change this library to support various size displays, part of that means we have to use malloc to assign the buffer. if you can't use it, there's probably other libraries you can use - but this one wont work for you :)
