### ISSUE TITLE
Support for 132x64 display

### ISSUE THREAD

**Issue by tprochazka** [adafruit/Adafruit_SSD1306#14]
Support for 132x64 OLED with SH1106 chip, which is compatible with SSD1306 woudl be nice. I tried to figure what changem but simply change 128 to 132 is not enought, it generate mess only on the display.

**Comment by hallard** [comment]
For those who're interested, I've just update my port of Adafruit Library to be able to run with SH1106. I started with the one dedicated to Raspberry PI
you can check out here http://hallard.me/adafruit-oled-display-driver-for-pi/
