### ISSUE TITLE
Make it work with Digispark

### ISSUE THREAD

**Issue by heltonbiker** [adafruit/Adafruit_SSD1306#141]
The docs for this project explicitly state that it doesn't work with ATTiny85.

I recently bought a Digispark and am a bit frustrated, since it would be awesome to use the GFX features (which I already used with ATMega), or at least a subset of them.

So is there any chance to make it work with ATTiny?
And if not, perhaps to include a _note_ so that people like me can understand the reasons and move on?

Thanks for this valuable library!

**Comment by dhalbert** [comment]
The ATTiny85 has a very small amount of RAM: only 512 bytes, not enough for this library.
