### ISSUE TITLE
How to flip screen 180 degrees.

### ISSUE THREAD

**Issue by gavron04** [adafruit/Adafruit_SSD1306#148]
- Arduino board:  micro 32u4

- Arduino IDE version 1.8.5

OLED 2,42" i2c SSD1306 128x64

Hello. I need to rotate my screen for 180 degress. But how to do that?

http://nerdclub-uk.blogspot.com/2016/03/adding-flip-function-to-adafruits.html - this cant works

https://forums.adafruit.com/viewtopic.php?f=47&t=25438 this also cant works

Some solution?

Regards

Fixed:

```
  } else if((WIDTH == 128) && (HEIGHT == 64)) {
    static const uint8_t PROGMEM init4b[] = {
      SSD1306_SETCOMPINS,                 // 0xDA
      0x12,
      SSD1306_SETCONTRAST };              // 0x81
	  ssd1306_command(SSD1306_COMSCANINC);
	  ssd1306_command(SSD1306_SEGREMAP);
    ssd1306_commandList(init4b, sizeof(init4b));
    ssd1306_command1((vccstate == SSD1306_EXTERNALVCC) ? 0x9F : 0xCF);
  }
```

**Comment by ladyada** [comment]
setRotation()

**Comment by lechenghhh** [comment]
setRotation 1   //=180
