### ISSUE TITLE
Raspberry PI4 - Raspian - SSD1306 library in nodejs and javascript or typescript 

### ISSUE THREAD

**Issue by yboujraf** [adafruit/Adafruit_SSD1306#162]
Dear @abachman , @martymcguire , @tannewt , @BenBergman , @microbuilder 

I am not using arduino for my project otherwise it will be very easy to implement my oled ssd1306 in I2C.
I need to use Raspberry PI4 with debian, nodejs, javascript or typescrypt.

Could anyone could route me on the correct link to find library compatible of my request or do I need to support C library but don't know if it is compatible with RaspberryPI4.

Best Regards,
Youssef

**Comment by ladyada** [comment]
hi we do not have a debian, nodejs, javascript or typescrypt library
