### ISSUE TITLE
The latest version does not work in platformio, today is September 24

### ISSUE THREAD

**Issue by yulong88888** [adafruit/Adafruit_SSD1306#185]
Hi guys, first of all thanks for this app for simplifying my work. Before August 10th, there was no problem in use, but now I have a problem.

I tried to use platformio to develop esp8266, and an error occurred during the compilation process. I used https://github.com/adafruit/Adafruit_SSD1306/blob/master/examples/ssd1306_128x64_i2c/ssd1306_128x64_i2c.ino, the program made some changes, I changed the setup () and loop() moved to the bottom of main.cpp, nothing more.

When I try to add #include <Adafruit_I2CDevice.h>, the compilation can pass, but the esp8266 will restart again and again after downloading.

Hope to get help, I will try my best to find the problem, thank you
![err](https://user-images.githubusercontent.com/22142323/94091646-54fb9e80-fe4b-11ea-85b1-34efb0713e80.png)

**Comment by ladyada** [comment]
https://github.com/adafruit/Adafruit_BusIO
