### ISSUE TITLE
Only some lines working

### ISSUE THREAD

**Issue by maikkel** [adafruit/Adafruit_SSD1306#197]
Hi, 
I tried running the ssd1306_128x64_i2c example, but it looks like this:
![vlcsnap-2021-01-04-12h36m26s027](https://user-images.githubusercontent.com/608838/103531595-f900d700-4e89-11eb-992b-eb5dc6f8acc4.png)
Only about 8 lines from the second one seem to work, the rest displays noise.
Is my oled broken (cheap no name one from china) or could it be something else?
I use a cheap esp32 from china (no name), otherwise works fine.

**Comment by ladyada** [comment]
hihi please contact the place you purchased OLED and ESP32 for tech support, they will have staff that can assist you!
