### ISSUE TITLE
Define OLED address instead of hard-coding

### ISSUE THREAD

**Issue by flywire** [adafruit/Adafruit_SSD1306#198]
Define OLED address like Screen Width/Height rather than hard-coding.

https://github.com/adafruit/Adafruit_SSD1306/blob/master/Adafruit_SSD1306.h#L87
>`#define SSD1306_SETDISPLAYOFFSET 0xD3    ///< See datasheet`

https://github.com/adafruit/Adafruit_SSD1306/blob/master/examples/ssd1306_128x32_i2c/ssd1306_128x32_i2c.ino#L63
>`  if(!display.begin(SSD1306_SWITCHCAPVCC, 0x3C)) { // Address 0x3C for 128x32`

https://github.com/adafruit/Adafruit_SSD1306/blob/master/examples/ssd1306_128x64_i2c/ssd1306_128x64_i2c.ino#L59
>`  if(!display.begin(SSD1306_SWITCHCAPVCC, 0x3D)) { // Address 0x3D for 128x64
`

**Comment by ladyada** [comment]
you can set the width/height on instantiation, thats where the allocation happens as well.

**Comment by flywire** [comment]
Agree but it would be nicer to use like:

``` C++
...
#define SCREEN_HEIGHT 32 // OLED display height, in pixels
#define ADDRESS 0x3D ///< See datasheet for Address; 0x3D for 128x64, 0x3C for 128x32
...
  if(!display.begin(SSD1306_SWITCHCAPVCC, ADDRESS)) {
...
```

I'd be happy to do a PR.

**Comment by ladyada** [comment]
that is not possible to do, a #define does not change the allocation inside the library

**Comment by ladyada** [comment]
wait, do mean just changing the *examples*? or the API?

**Comment by flywire** [comment]
Just the examples so `SCREEN_ADDRESS` (or preferred name) is identified more clearly.

**Comment by ladyada** [comment]
oooh ok yes thats ok! sorry we get tons of people trying to change the API... yes a PR is welcome, please note it has to pass CI
https://learn.adafruit.com/contribute-to-arduino-with-git-and-github
