### ISSUE TITLE
Feature Request: Make Splash Optional

### ISSUE THREAD

**Issue by jarruda** [adafruit/Adafruit_SSD1306#205]
The Adafruit splash consumes over 5k of flash and adds the CPU cost of a `drawBitmap` call to `begin`.

It would be nice if this were optional.

I would be happy to provide a PR.

**Comment by ShivamJoker** [comment]
Why no updates on this ?

**Comment by jacobisbell** [comment]
Agreed. Seems like a no-brainer.
