### ISSUE TITLE
warning: 'B00000000' is deprecated: use 0b00000000

### ISSUE THREAD

**Issue by montoyamoraga** [adafruit/Adafruit_SSD1306#208]
- Arduino board:  Arduino Nano 33 BLE Sense

- Arduino IDE version \1.8.13

- List the steps to reproduce the problem below (if possible attach a sketch or
  copy the sketch code in too): **LIST REPRO STEPS BELOW**

I am using this library as a dependency on a project, and when compiling I get many warnings like these:

In file included from /home/runner/Arduino/libraries/Adafruit_SSD1306/Adafruit_SSD1306.cpp:54:0:
  /home/runner/Arduino/libraries/Adafruit_SSD1306/splash.h:10:60: warning: 'B00000000' is deprecated: use 0b00000000 instead [-Wdeprecated-declarations]
       B11000000, B00000000, B00000000, B00000000, B00000000, B00000000,

**Comment by ladyada** [comment]
hi please submit a PR :)
