### ISSUE TITLE
Lag / Glitch issue

### ISSUE THREAD

**Issue by Marv63** [adafruit/Adafruit_SSD1306#219]
- Arduino board:  ESP32
- Arduino IDE version: 1.8.15

- List the steps to reproduce the problem below (if possible attach a sketch or
  copy the sketch code in too): Got the ESP32 DEV board, set it up in adruino ide. Uploaded the Example code from the example list. (The librarys were already installed from adruino projects). Connected the ESP like that. Uploaded it. 
![image](https://user-images.githubusercontent.com/15062841/132565194-7839eb99-f22f-456b-beda-25b28f77ae53.png)
Result: https://www.youtube.com/watch?v=sqOtl-lKHZc (the diagonal lines of wandering pixels isn´t visible its just because i recorded it i guess)
The first logo of adafruit is weird. all animations are lagging and looking shifting pixels. I don´t know. The last sequence goes very fast too. Text looks ok most of the time but sometimes the pixel shift too.
I don´t know what could possibly fix this. There aren´t any cases like this expect one on reddit with an awnser that that problem doesn´t exist.

Oh and the GFX&SSD1306 are tested with the newest and 2nd newest release: same result.

Would be glad if somebody could help

**Comment by ladyada** [comment]
hihi - please contact the seller you bought the OLED from to get wiring/tech support. we dont know what exactly you're using and its probably a hardware issue. thanks :)
