### ISSUE TITLE
Incompatibility with library Adafruit SSD1306 Wemos Mini Oled, on an Wemos D1 mini ESP32

### ISSUE THREAD

**Issue by Escrich** [adafruit/Adafruit_SSD1306#231]
Dear all, every time you try to send a simple sketch from Arduino 1.8.16 IDE to the Wemos D1 mini ESP32, you need not to have this library on library folder of your Arduino IDE, I was tried with my normally installed version, and even with last released version of this library, and my conclusion it's so clear, you cannot have this library if you have the Adafruit SSD1306 Wemos Mini Oled in same libraries folder, enclosed you'll find the sketch to show you the problem, a printout showing the output of ESP32 crashing again and again, and a list of my installed libraries, I was tried to uninstall every single library and make a new try after every change , getting a final consideration, it's not possible at all to have both libraries at same time working, but, in the past, may be six months ago, both libraries were working together without any problem, I was tried old versions of Adafruit_SSD1306, but not older versions of "Adafruit SSD1306 Wemos Mini Oled Library".
Thanks for your attention.
Regards:
JMEC

[_20201227_SHT30_OLED_Humedad_y_temperatura.ino.txt](https://github.com/adafruit/Adafruit_SSD1306/files/7794734/_20201227_SHT30_OLED_Humedad_y_temperatura.ino.txt)
![Hanging ESP32](https://user-images.githubusercontent.com/45154631/147790972-13c4614c-d626-4158-bc1a-1dc3a6a4b801.png)
![Librerias SSDF1306 Instaladas](https://user-images.githubusercontent.com/45154631/147790990-c7aac5f5-26e5-4721-a65b-44b0c35626de.PNG)

**Comment by Escrich** [comment]
This is the library working in the past

[Adafruit_SSD1306_Wemos_Mini_OLED.zip](https://github.com/adafruit/Adafruit_SSD1306/files/7794790/Adafruit_SSD1306_Wemos_Mini_OLED.zip)

**Comment by Escrich** [comment]
Display is still working with library https://github.com/stblassitude/Adafruit_SSD1306_Wemos_OLED, always having not Adafruit_SSD1306 installed on same libraries folder

**Comment by skyflyer** [comment]
I can confirm that the above-referenced older version of the lib is working on Wemos D1 mini (ESP8266) with OLED shield v.1.1.0.
