### ISSUE TITLE
Multiple Display doesn't work with 128x64 display size

### ISSUE THREAD

**Issue by djs45** [adafruit/Adafruit_SSD1306#237]
Hello.
I have a project who use multiple SSD1306 128x64 display with arduino in SPI mode.
My code work in 128x32 mode but when I turn it to 128x64 (native display screen), nothing is displayed.
What is the problem ?

My code : 

#include <SPI.h>
#include <Adafruit_GFX.h>
#include <Adafruit_SSD1306.h>

#define OLED_MOSI  4  //2
#define OLED_CLK   3  //1
#define OLED_DC    5  //4
#define OLED_CS    7  //5
#define OLED_RESET 6  //3
#define OLED_CS2    8  //5

#define SCREEN_WIDTH 128 // OLED display width, in pixels
#define SCREEN_HEIGHT 32 // OLED display height, in pixels

Adafruit_SSD1306 display1(SCREEN_WIDTH,SCREEN_HEIGHT, OLED_MOSI, OLED_CLK, OLED_DC, OLED_RESET, OLED_CS);
Adafruit_SSD1306 display2(SCREEN_WIDTH,SCREEN_HEIGHT, OLED_MOSI, OLED_CLK, OLED_DC, -1, OLED_CS2);

void setup() {
  Serial.begin (9600);
  display1.begin(SSD1306_SWITCHCAPVCC,0);
  display1.clearDisplay();
  display2.begin(SSD1306_SWITCHCAPVCC,0);
  display2.clearDisplay();
}

void loop() {  
  display1.begin(SSD1306_SWITCHCAPVCC,0);
  display1.clearDisplay();
  display1.setTextSize(2,1);
  display1.setTextColor(WHITE);
  display1.setCursor(0, 0);
  display1.println("SHOOT");
  display1.println("ADV. SHOOT");
  display1.println("TURN ACW");
  display1.println("SAVE POS");
  display1.display();

  display2.begin(SSD1306_SWITCHCAPVCC,0);
  display2.clearDisplay();
  display2.setTextSize(2,1);
  display2.setTextColor(WHITE);
  display2.setCursor(0, 0);
  display2.println("LOAD");
  display2.println("SAVE");
  display2.println("OVERWRITE");
  display2.println("RESET");
  display2.display();
}

**Comment by bfarnam** [comment]
I had the same issue... you can see how I resolved it to use 2 128x64 displays on a 328p (pro mini or orig UNO) here:https://github.com/adafruit/Adafruit_SSD1306/issues/242
