### ISSUE TITLE
Won't compile for RP2040 due to pgm_read_byte macro

### ISSUE THREAD

**Issue by caternuson** [adafruit/Adafruit_SSD1306#239]
Re this thread:
https://forums.adafruit.com/viewtopic.php?f=57&t=189849

Can recreate by attempting to compile any library example for any RP2040 target board from earlephilhower core.

Looks like the preproc logic needs some updating to just `#include <pgmspace.h>` for RP2040:
https://github.com/adafruit/Adafruit_SSD1306/blob/d6db01d87fe5cff5649993f1c6c3064db6a09ec7/Adafruit_SSD1306.cpp#L39-L46

**Comment by ladyada** [comment]
erg ok wanna add and also add rp2040 to the CI list?

**Comment by caternuson** [comment]
Fixed with #240
