### ISSUE TITLE
pgmspace.h: No such file or directory for Raspberry Pi Pico

### ISSUE THREAD

**Issue by ghost** [adafruit/Adafruit_SSD1306#259]
- Arduino board:  Raspberry Pi Pico
- Arduino IDE version: 2.0.3
- Using Arduino Mbed OS RP2040 Boards (installed from Arduino's board manager) to program the Pico

The error I get when trying to compile the example file "ssd1306_128x64_12c" is the following:

Adafruit_SSD1306.cpp:42:10: fatal error: pgmspace.h: No such file or directory

Lines 39-42 of such cpp file looks like this:
#ifdef __AVR__
#include <avr/pgmspace.h>
#elif defined(ESP8266) || defined(ESP32) || defined(ARDUINO_ARCH_RP2040)
#include <pgmspace.h>

If I modify line 42 like this:
#include <avr/pgmspace.h>
then the sketch compiles and works as expected.

So it seems that the Pico uses the avr pgmspace, maybe this can be modified in the cpp file
Thanks!

**Comment by cscott** [comment]
It works fine if you use version 2.5.1 fwiw:
```
lib_deps = 
	adafruit/Adafruit SSD1306@2.5.1
```
(Don't use the `^` symbol after the `@` sign or it will use "a version compatible with 2.5.1" and it thinks that 2.5.2 and above are "compatible".)

**Comment by cscott** [comment]
Seems like https://github.com/adafruit/Adafruit_SSD1306/commit/3fb7221784be255fae7b4eba219039e398aed442 is at fault; they added support for the RP2040 Feather and somehow broke the RP2040 pico in the process.

**Comment by germtown** [comment]
Switching to 2.5.1 (from 2.5.7) worked for me to get things building, I feel lucky this was my first search result!

**Comment by jptp13** [comment]
Hi
Same issue for Arduino Nano ESP32
"Compilation error: avr/pgmspace.h: No such file or directory"
Any workaround?
Thanks

**Comment by ladyada** [comment]
merged!
