### ISSUE TITLE
Teensy issue on top row.

### ISSUE THREAD

**Issue by fedekrum** [adafruit/Adafruit_SSD1306#267]
Hi,
I am not sure why but after a while of running a sketch the top row acts as the bottom row.
Here you have a video.
[![Watch the video](https://img.youtube.com/vi/fBTlQu63RdQ/default.jpg)](https://youtu.be/fBTlQu63RdQ)
Executing the demo file on the examples is enough to get this issue.
This issue is being discussed deeply on https://forum.pjrc.com/threads/73161-Adafruit-SSD1306-lib-top-row-behaves-as-bottom-row-after-a-while.

**Comment by fedekrum** [comment]
The problem was that the Teensy 3.0 has no pull-up resistors.
More details at the link above.
Thanks to @PaulStoffregen for his investigation and for the Teensy family of boards !!

**Comment by fedekrum** [comment]
The problem was that the Teensy 3.0 has no pull-up resistors.
More details at the link above.
Thanks to @PaulStoffregen for his investigation and for the Teensy family of boards !!

**Comment by PaulStoffregen** [comment]
Genuine Adafruit displays have the proper pullup resistors.
