### ISSUE TITLE
compatibility with mpu6050

### ISSUE THREAD

**Issue by momotaro1979** [adafruit/Adafruit_SSD1306#33]
Hello,

I use a 128x64 oled with arduino uno and it works perfectly.

I use a GY521 with freeimu at the same arduino (even installed parallel to the oled) and it works perfectly.

So both components work perfectly even when they are installed electrically parallel to each other.

But when I want to use IMU data to modify screen content (I comment in adafruit library and use the display) at the same time as my freeimu i simply don't get ypr values. some other raw values seem to be not affected...

As I'm totally new to Arduino, I2C,... could there be any incompatibility problems ? 

best regards 

M

**Comment by PaintYourDragon** [comment]
Out of RAM. There's typically about 1.7K RAM available for Arduino sketches. The SSD1306 has no display buffer of its own and must be handled by the Arduino, consuming 1K for a 128x64 display. IMU code is pretty complicated and needs more than the available remaining space.

Needs either a less memory-intensive display (128x32 OLED uses half the RAM, or various color LCD displays have their own internal buffer), or an Arduino-compatible board with more RAM (e.g. Arduino Mega, or possibly Leonardo or Micro, which have an extra 512 bytes, may or may not be enough).
