### ISSUE TITLE
raspberry pi support

### ISSUE THREAD

**Issue by FishTest** [adafruit/Adafruit_SSD1306#37]
can it directly support raspberry pi ?
I hope there's a c/c++ version of Adafruit_SSD1306 library.

**Comment by t3chguy** [comment]
https://learn.adafruit.com/ssd1306-oled-displays-with-raspberry-pi-and-beaglebone-black/overview
https://github.com/adafruit/Adafruit_Python_SSD1306

**Comment by FishTest** [comment]
I know that ,but i hope there will be a c /c++ version

**Comment by microbuilder** [comment]
This version is only for Arduino.  Anything for the Pi would require an entirely different codebase and code structure.
