### ISSUE TITLE
Add support for HUZZAH ESP8266 Breakout

### ISSUE THREAD

**Issue by honkbonk** [adafruit/Adafruit_SSD1306#38]
There's branch of this library ( https://github.com/somhi/ESP_SSD1306 ) but I'm having a hard time getting the Huzzah ESP8266 Breakout and the Monochrome 1.3" 128x64 OLED graphic display (https://www.adafruit.com/products/938) to work with that library.  

If there are some good resources available I'd take that as a starting point.

This persons claims to have success but I can't repeat his setup...

https://bagaloozy.wordpress.com/2015/07/14/cutting-the-cord-epg-getting-the-ssd1306sh1106-oled-working-with-esp8266/

Thanks

**Comment by microbuilder** [comment]
This should work with #44
