### ISSUE TITLE
how to create my own logo

### ISSUE THREAD

**Issue by geetee24** [adafruit/Adafruit_SSD1306#53]
I need to create my own logo. 

can you document the process of what tools you used to create the adafruit logo in the buffer() in Adafruit_SSD1306.cpp so that I can do it for my own jpg?

Thanks

**Comment by Effix** [comment]
https://learn.adafruit.com/monochrome-oled-breakouts/arduino-library-and-examples

This page has a link to and shows how to use "LCD Assistant" to convert bitmaps into code.

**Comment by mcauser** [comment]
I found this too quite useful: http://javl.github.io/image2cpp/
Upload a bitmap to get a byte array.
Use draw mode vertical / horizontal to orient the pixels.

_From memory_, the buffer uses vertical and drawBitmap() uses horizontal.

**Comment by x4m3** [comment]
<http://javl.github.io/image2cpp/> is very useful, and it helped me to make my own logo.

i made the logo in photoshop in 128x64 (the resolution of the display i am using), exported the image as bmp, uploaded it to the online tool, copied the arduino code, pasted into my program, and worked like a charm!

<https://github.com/vegapoubelle/morpheus/tree/master/logo-ecran>
