### ISSUE TITLE
Support for Odroid C1/C1+/C2 ?

### ISSUE THREAD

**Issue by codewarriorFX** [adafruit/Adafruit_SSD1306#67]
Im looking to use the Adafruit 128x64 OLED displays via I2C with the Odroid C2 board. The operating system is based on Debian linux. Would this library work on this environment? I already installed the i2c drivers for this board. Thanks.

**Comment by ladyada** [comment]
you'd probably want to do it in python: https://github.com/adafruit/Adafruit_Python_SSD1306
