### ISSUE TITLE
Wrong CRC when trying to install library from arduino  IDE

### ISSUE THREAD

**Issue by Netoperz** [adafruit/Adafruit_SSD1306#74]
ver. 1.1.0 - IDE 1.6.12
OS X Sierra 10.12.1

Installing ssd1306 library from library manager in Arduino IDE shows CRC Error of the library

I'm trying to use the library on Wemos D1 Retired ESP8266 board

**Comment by ladyada** [comment]
weird, well, i bumped the version!
