### ISSUE TITLE
Two minor documentation updates needed

### ISSUE THREAD

**Issue by MartyMacGyver** [adafruit/Adafruit_SSD1306#77]
The README should reflect that this works with the ESP32 (I've tested against a 128x32 display and it works fine).

It would also be very useful to mention in the examples that if RST (reset) is not being used you can set it to `-1`, e.g.:

    Adafruit_SSD1306 display(-1);  // More explicit

or (because the default argument to that constructor is -1):

    Adafruit_SSD1306 display;

**Comment by PaintYourDragon** [comment]
Mentioned in README and example code now. Thanks!
