### ISSUE TITLE
Reading from GDDRAM

### ISSUE THREAD

**Issue by sglvladi** [adafruit/Adafruit_SSD1306#78]
Hi guys,

Looking at the library, I couldn't identify any function that would allow us to read and possibly store the current contents of the screen (i.e. in form of a 128x64 binary pixel map or something). 

Also, reading page 33 of the [datasheet](https://cdn-shop.adafruit.com/datasheets/SSD1306.pdf) gives me a hint that such a functionality is provided. Since I am only just starting to go as low level as raw i2c, I was wondering if anyone has written code that could implement this?

If not, could anyone please confirm or reject my intuition about whether or not this is possible, and if it is possible maybe point me to the right direction?

Thanks much in advance!

**Comment by PaintYourDragon** [comment]
From section 9.1: "No data read is provided in serial mode operation." It's available only in 6800 and 8080 parallel modes, which the breakout doesn't provide and library doesn't support.
