### ISSUE TITLE
ESP8266: I2C transmission rate stays at 100kHz

### ISSUE THREAD

**Issue by KarateBrot** [adafruit/Adafruit_SSD1306#80]
### Adafruit_SSD1306.cpp, line 461 - 464
```cpp
#ifdef TWBR
  uint8_t twbrbackup = TWBR;
  TWBR = 12; // upgrade to 400KHz!
#endif
```

When using **ESP boards** these lines seem to **get ignored** so the **I2C rate stays at 100 kHz**. 

The problem here is that **Adafruit_SSD1306::display** takes way too long to transmit data with 100 kHz and therefore yielding only ~10 fps on my display which is way too slow. You can actually see every frame building up. :snail:

I tried this on a WeMos D1 Mini (4MB) and on a NodeMCU. 

---

- ### How I fixed it
In `void setup(){}` I inserted `Wire.setClock(400000L);` to successfully get 400 kHz on my ESP boards and ~30 fps on my display.
```cpp
void setup()
{
  Wire.setClock(400000L);
}
```

- ### Possible solution
Add code to **Adafruit_SSD1306.cpp, line 465**:
```cpp
#ifdef TWBR
  uint8_t twbrbackup = TWBR;
  TWBR = 12; // upgrade to 400KHz!
#endif
 
#ifdef ESP8266
  Wire.setClock(400000L);
#endif

```
---
### Additionally:
In this case an 800 kHz transmission rate seems to be the maximum. By calling `Wire.setClock(800000L);` ~60 fps can be achieved on SSD1306 OLEDs using an ESP8266. That's nearly a **_sixfold increase in drawing speed!_** compared to what's possible out of the box right now.

**Comment by guru-florida** [comment]
As suggested above, adding this to Adafruit_SSD1306 worked for me. My drawing went from 112ms to 30ms...9fps to 30fps!  Thanks @KarateBrot !!
```
#ifdef ESP8266
  Wire.setClock(800000L);
#endif
```
Trying to set in setup() didnt work. The Adafruit lib (or Wire) resets it back to 100k.

**Comment by KarateBrot** [comment]
> Trying to set in setup() didnt work. The Adafruit lib (or Wire) resets it back to 100k.

It only worked for me if I put the function call at the end of the `Setup()` routine. 
This way `Wire.setClock()` ultimately overrides the `Wire` settings no matter what.

**Comment by PaintYourDragon** [comment]
Library v1.2 incorporates faster I2C transfers.
