### ISSUE TITLE
 If display.setTextSize(4) numbers are pixelized/poor quality.

### ISSUE THREAD

**Issue by dpiralis** [adafruit/Adafruit_SSD1306#81]
When I display large number they are pixelized like display has only 10x5 pixels. That looks awful, how to fix this?

[![18426818_10208781228835850_1484758118_o.jpg](https://s1.postimg.org/7sx8ye50v/18426818_10208781228835850_1484758118_o.jpg)](https://postimg.org/image/kx2tb2x2j/)

**Comment by PaintYourDragon** [comment]
https://learn.adafruit.com/adafruit-gfx-graphics-library/using-fonts
