### ISSUE TITLE
Use of "CS" as variable name

### ISSUE THREAD

**Issue by JRDavisUF** [adafruit/Adafruit_SSD1306#86]
I've been successfully able to use this software with my Msp432 Launchpad using Energia, but I did run into one annoying issue.

In Adafruit_SSD1306::Adafruit_SSD1306 the variable name "CS" is used.  CS is already #define'ed by TI in some of their driverlib stuff.  As such, one gets a ton of (no-so-obvious) errors when trying to compile.  It would be appreciated if another variable name could be used.  Personally, I just suffixed all these short 2-capital letter variables in this part of the code with _SSD1306.

thx.

**Comment by PaintYourDragon** [comment]
Fixed as of v1.2.4. Thanks!
