### ISSUE TITLE
Instantiation of an `Adafruit_SSD1306` object should optionally  take a `Wire` object.

### ISSUE THREAD

**Issue by spmp** [adafruit/Adafruit_SSD1306#99]
Instantiation of an `Adafruit_SSD1306` object should optionally  take a `Wire` object.
 In cases where there is more than one I2C (or `Wire`) device modification of the  `Adafruit_SSD1306` library code is required - or worse to be copied and renamed.
 Given that `Adafruit_SSD1306` is dependent on `Wire`, and that more than one `Wire` object can be in use in a single project, then the instantiation of `Adafruit_SSD1306` needs to have the `Wire` object as a parameter, with sensible default if not provided to preserve backward compatibility.

**Comment by PaintYourDragon** [comment]
Implemented in v1.2 -- new constructors added, including one that accepts a Wire argument.
